# Generated by Django 4.2.2 on 2023-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internapp', '0002_user_role_alter_data_quantity_alter_data_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
